#! /usr/bin/env python

from gi.repository import Gtk, GLib
import os,time

#Hack for pygtk ignoring ^C
import signal
signal.signal(signal.SIGINT, signal.SIG_DFL)

class Battery():
    def __init__(self, id):
        self.id = id
        self.voltage = self.get("voltage_now") / 1000
        try:
          self.max = self.get("energy_full") * 1000 / self.voltage
          self.orig_max = self.get("energy_full_design") * 1000 / self.voltage
          self.now = self.get("energy_now") * 1000 / self.voltage
          self.state = self.get("status") == "Charging"
          self.rate = self.get("power_now") / self.voltage
        except:
          self.max = self.get("charge_full") / 1000
          self.orig_max = self.get("charge_full_design") / 1000
          self.now = self.get("charge_now") / 1000
          self.state = self.get("status") == "Charging"
          self.rate = self.get("current_now") / 1000

    def get (self, attr):
        with open (os.path.join ("/sys/class/power_supply",self.id,attr)) as f:
          line = f.readline().strip()
          return line if attr == "status" else int(line)

    def get_percent (self):
        return int(self.now) / float(self.max)

    def get_designpercent (self):
        return int(self.now) / float(self.orig_max)

    def ttl (self):
        if self.state: ttl = 3600 * (self.max - self.now) / self.rate
        else: ttl =  3600 * self.now / self.rate

        return time.strftime ("%T", time.gmtime(ttl))

    def __str__ (self):
        return "Battery %s: %s %.2f%% (%.2f%% of design capacity), %s remaining" % (self.id, "Charging" if self.state else "Discharging", self.get_percent()*100, self.get_designpercent()*100, self.ttl())

class TrayIcon():
    def __init__(self):
        self.icon = Gtk.StatusIcon()
        self.icon.embedded = True;
        self.last_state = "";
        self.update_icon()
        self.icon.set_visible(True)
        GLib.timeout_add_seconds(5, self.update_icon)

    def destroy (self, widget, data=None):
        Gtk.main_quit()

    def main(self):
        Gtk.main()

    def update_icon(self):
        self.batteries = {}
        for entry in os.listdir ("/sys/class/power_supply"):
          if "BAT" in entry:
            self.batteries[entry] = Battery(entry)

        if not self.batteries:
          self.icon.set_from_stock(Gtk.STOCK_CONNECT)
          self.icon.set_tooltip_text("No battery found.")
          return True

        status = 0
        charging = False
        for battery in self.batteries:
          status += self.batteries[battery].get_percent()
          charging |= self.batteries[battery].state
        status /= len(self.batteries)
        if status < 0.25:   state = "crit"
        elif status < 0.5:  state = "low"
        elif status < 0.75: state = "high"
        else:               state = "full"

        self.icon.set_tooltip_text ("\n".join([str(self.batteries[battery]) for battery in self.batteries]))
        if status != self.last_state:
          self.icon.set_from_file("/usr/share/pixmaps/battery/battery-"+state+("-full.png" if status==1 else "-loading.png" if charging else ".png"))
        self.last_state = status

        return True

if __name__ == "__main__":
    i = TrayIcon()
    i.main()
